### ISSUE TITLE
`antfu/no-only-tests` rule

### ISSUE THREAD

**Issue by pauliesnug** [antfu/eslint-plugin-antfu#21]
### Clear and concise description of the problem

Right now, I use [eslint-plugin-no-only-tests](https://github.com/levibuzolic/eslint-plugin-no-only-tests/blob/main/rules/no-only-tests.js) to enforce stylistically. I wish that this could be ported to a more flat config friendly setup with types and recent ESLint apis.

### Suggested solution

We could port this plugin to TypeScript and add it

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I am not interested in porting and maintaining a rule unless it's deprecated.

This is a one-rule plugin, I am pretty sure it doesn't need to do anything to work in flat config. https://github.com/antfu/eslint-config/blob/main/src/configs/test.ts

If it has to be, I'd suggest it goes to https://github.com/veritem/eslint-plugin-vitest
