### ISSUE TITLE
why? no-top-level-await

### ISSUE THREAD

**Issue by thisVioletHydra** [antfu/eslint-plugin-antfu#33]
### Clear and concise description of the problem

`no-top-level-await`, 
why should I use this rule?
And what should I do with the already established rule: [prefer-top-level-await](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v56.0.0/docs/rules/prefer-top-level-await.md)

### Suggested solution

please explain

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Top-level await might make sense for CLI based Node.js apps. But for any other cases, library, web apps, it's always something better to avoid.
